name: sampleCI

on:
  push:
    branches: [ master ]

jobs:
  job1:
    name: first job
    runs-on: ubuntu-20.04
    steps:
    - name: Run a one-line script
      run:  echo Hello, World!

  pytest:
    name: python job
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: x64
      - name: Display python version
        run: python -c "import sys; print(sys.version)"
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip          
          pip install -r requirements.txt
      - name: Run test
        run: pytest

  dockertest:
    name: docker test job
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set up Docker
          run: |
            docker-compose up -d
        - name: Run test
          run: docker-compose exec -T python pytest